backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: 'product_types'
    label: 'Product Types'
    folder: 'src/pages/product-types'
    create: true
    identifier_field: name
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'string' }
  - name: 'products'
    label: 'Products'
    folder: 'src/pages/products'
    create: true
    identifier_field: name
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - {
          label: 'Product Type',
          name: 'product_type',
          widget: 'relation',
          collection: 'product_types',
          searchFields: ['name', 'category'],
          valueField: 'name',
          displayFields: ['{{category}} - {{name}}'],
        }
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: About,
              name: about,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - {
              label: Network,
              name: network,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: Products,
              name: products,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Categories,
                    name: categories,
                    widget: list,
                    fields:
                      [
                        { label: Label, name: label, widget: string },
                        {
                          label: Images,
                          name: images,
                          widget: list,
                          fields:
                            [
                              { label: Source, name: source, widget: image },
                              { label: Name, name: name, widget: string },
                            ],
                        },
                      ],
                  },
                ],
            }
